### PR TITLE
Issue77

### PR DESCRIPTION
**Pull request by xmclark**
Add master and dev badges to readme

### CODE REVIEW

**Comment by DannyPeck** [comment]
Should we make columns for each of the three badges?

**Review by DannyPeck — COMMENTED** [review]
Should we make columns for each of the three badges?

**Comment by xmclark** [comment]
@DannyPeck you want the license badge to go in its own row?

**Comment by DannyPeck** [comment]
@xmclark I think that is fine, I wonder if this would look better if it was centered and there were column lines in the table.

**Comment by xmclark** [comment]
I was able to center the table by using a div with align center

**Review by DannyPeck — APPROVED** [review]

**Pull request merged**
