### PR TITLE
Add test modules for code coverage

### PR DESCRIPTION
**Pull request by xmclark**
Add test modules so that all code can be tracked under test code coverage. 
Code coverage was changed to tarpaulin because of better Rust support.

### CODE REVIEW

**Comment by xmclark** [comment]
Coveralls is blocking because code coverage went down, but that was the point of this or.

**Review by DannyPeck — DISMISSED** [review]

**Comment by DannyPeck** [comment]
Feel free to merge :).

**Comment by xmclark** [comment]
wow I have been not on my personal github for awhile lol

**Comment by xmclark** [comment]
sorry for the merge fiasco, this is ready to review @DannyPeck @technetos

**Review by DannyPeck — APPROVED** [review]

**Pull request merged**
