### PR TITLE
first pass at travis-ci code coverage

### PR DESCRIPTION
**Pull request by DannyPeck**

### CODE REVIEW

**Review by xmclark — DISMISSED** [review]

**Comment by xmclark** [comment]
So it seems like cargo-travis is not too well supported anymore, according to this issue https://github.com/huonw/travis-cargo/issues/72. Luckily there is an alternative called *cargo-travis*. It seems to have feature parity with the deprecated package we use now.

**Comment by xmclark** [comment]
alright @DannyPeck @technetos we've got ourselves some sweet code coverage on the coveralls.io. 

only thing remaining that I would like to add is a badge, but there is a small issue with that because the branch is hard coded in the url. This causes problems when we merge back to master (someday...). See this: https://stackoverflow.com/questions/18673694/referencing-current-branch-in-github-readme-md.

**Comment by technetos** [comment]
lol travis-cargo is dead long live cargo-travis

**Comment by DannyPeck** [comment]
I have found an example of someone using git precommit hooks to modify the badge url: https://gist.github.com/cfont/c0f44703b933c54c9f1b.

**Comment by DannyPeck** [comment]
Here is a tutorial on Git Hooks: https://www.atlassian.com/git/tutorials/git-hooks.

**Comment by DannyPeck** [comment]
Git Hooks are honestly really cool, I think we should look into other possible hooks we could integrate into our project.

**Comment by DannyPeck** [comment]
Noting that because I can't approve my own PR, I approve of the changes @xmclark added.

**Comment by DannyPeck** [comment]
Are we still waiting on the addition of precommit badges on this PR?

**Comment by technetos** [comment]
I believe so yes

**Comment by xmclark** [comment]
I think Travis may be able to help us out with post merge readme commit.

**Review by xmclark — APPROVED** [review]

**Review by technetos — APPROVED** [review]

**Pull request merged**
